version: '3'

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: todo

      KC_HOSTNAME_URL: https://kdp-ediaqi.know-center.at/keycloak
      KC_HOSTNAME_ADMIN_URL: https://kdp-ediaqi.know-center.at/keycloak
      KC_HOSTNAME_PORT: 8502
      #KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: true
      #KC_PROXY: edge
      #KCS_FRONTEND_URL: https://kdp-ediaqi.know-center.at/keycloak

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: todo
      KEYCLOAK_ADMIN_PASSWORD: todo
    command: 
      - start-dev
      # - --proxy-headers=xforwarded
       #- --hostname-strict=false
       #- --hostname-strict-https=false
    depends_on:
      - keycloakdb
    ports:
      - 8502:8080

  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
volumes:
    postgres_data: